### ISSUE TITLE
mockall fails with rust beta and nightly

### ISSUE THREAD

**Issue by MOZGIII** [asomers/mockall#118]
Our tests started failing at CI recently:

```
thread 'pubnub::tests::mocked_pubnub_subscribe_ok' panicked at 'attempted to leave type `std::mem::ManuallyDrop<std::cell::UnsafeCell<std::boxed::Box<std::boxed::Box<dyn std::ops::FnOnce() -> mock::runtime::gen::MockRuntime>>>>` uninitialized, which is invalid', /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libcore/mem/mod.rs:661:5
stack backtrace:
   0:     0x55c2bab910e4 - backtrace::backtrace::libunwind::trace::h84ad83e98b76789a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55c2bab910e4 - backtrace::backtrace::trace_unsynchronized::h2e1111a841a6f2eb
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55c2bab910e4 - std::sys_common::backtrace::_print_fmt::h4ed20bfa1f13cf08
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55c2bab910e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h213283d7cb6022f7
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55c2babba42c - core::fmt::write::hc7a8fb823232cfdf
                               at src/libcore/fmt/mod.rs:1069
   5:     0x55c2ba93ba55 - std::io::Write::write_fmt::ha20320e408325563
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/io/mod.rs:1504
   6:     0x55c2bab8b391 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::hcbffb6bf78171cdb
                               at src/libstd/io/impls.rs:156
   7:     0x55c2bab939b5 - std::sys_common::backtrace::_print::h500728f0841aa084
                               at src/libstd/sys_common/backtrace.rs:62
   8:     0x55c2bab939b5 - std::sys_common::backtrace::print::h0f1208d67d691e76
                               at src/libstd/sys_common/backtrace.rs:49
   9:     0x55c2bab939b5 - std::panicking::default_hook::{{closure}}::hbc544d3b12e7f56c
                               at src/libstd/panicking.rs:198
  10:     0x55c2bab9369b - std::panicking::default_hook::h428795d6ada6fa37
                               at src/libstd/panicking.rs:215
  11:     0x55c2bab94012 - std::panicking::rust_panic_with_hook::h470c3957a5dcdc74
                               at src/libstd/panicking.rs:511
  12:     0x55c2bab93bfb - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  13:     0x55c2babb8e11 - core::panicking::panic_fmt::h083ba5b0701f197b
                               at src/libcore/panicking.rs:111
  14:     0x55c2babb8d5d - core::panicking::panic::hf78e1fa57a429489
                               at src/libcore/panicking.rs:54
  15:     0x55c2ba88e106 - core::mem::uninitialized::h420e643c07c40c0c
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libcore/mem/mod.rs:661
  16:     0x55c2ba88e106 - fragile::fragile::Fragile<T>::into_inner::hba57b7c3ce462529
                               at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/fragile-0.3.0/src/fragile.rs:70
  17:     0x55c2ba9039ca - pubnub_core::mock::runtime::gen::__mock_Runtime_Clone::clone::Rfunc::call_mut::hc87453e1a39e6f6d
                               at pubnub-core/src/mock/runtime.rs:13
  18:     0x55c2ba9040f0 - pubnub_core::mock::runtime::gen::__mock_Runtime_Clone::clone::Expectation::call::hd6ba2c116af3f357
                               at pubnub-core/src/mock/runtime.rs:13
  19:     0x55c2ba905335 - pubnub_core::mock::runtime::gen::__mock_Runtime_Clone::clone::Expectations::call::{{closure}}::h23db96caf4407ce3
                               at pubnub-core/src/mock/runtime.rs:13
  20:     0x55c2ba8aef20 - core::option::Option<T>::map::h7f71317a0fd282a4
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libcore/option.rs:456
  21:     0x55c2ba9043d1 - pubnub_core::mock::runtime::gen::__mock_Runtime_Clone::clone::Expectations::call::h1586cce6fc551de3
                               at pubnub-core/src/mock/runtime.rs:13
  22:     0x55c2ba8d3113 - <pubnub_core::mock::runtime::gen::MockRuntime as core::clone::Clone>::clone::h456124a96b29f3f3
                               at pubnub-core/src/mock/runtime.rs:13
  23:     0x55c2ba8c4c4d - pubnub_core::subscription::subscribe_loop_supervisor::SubscribeLoopSupervisor::subscribe::{{closure}}::hee7a1afb3c8d7323
                               at pubnub-core/src/subscription/subscribe_loop_supervisor.rs:146
  24:     0x55c2ba8f9810 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h32046795d2aab64e
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libcore/future/mod.rs:66
  25:     0x55c2ba8cb68a - pubnub_core::pubnub::subscribe::<impl pubnub_core::pubnub::PubNub<TTransport,TRuntime>>::subscribe::{{closure}}::h8831729c67d3415a
                               at pubnub-core/src/pubnub/subscribe.rs:46
  26:     0x55c2ba8f9c10 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb960d7f089d69311
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libcore/future/mod.rs:66
  27:     0x55c2ba8d615b - pubnub_core::pubnub::tests::mocked_pubnub_subscribe_ok::{{closure}}::h160e5f7fda6e59d6
                               at pubnub-core/src/pubnub/tests.rs:163
  28:     0x55c2ba8f9b57 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha4add71a4cb5fa62
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libcore/future/mod.rs:66
  29:     0x55c2bab6937c - <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::h1b19c9c578225d94
                               at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.4/src/future_obj.rs:86
  30:     0x55c2bab662c7 - <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next::hd82a6be447485085
                               at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/futures_unordered/mod.rs:544
  31:     0x55c2bab6728c - futures_util::stream::stream::StreamExt::poll_next_unpin::hb2711b80bf7eeb64
                               at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/stream/stream/mod.rs:1184
  32:     0x55c2bab5f792 - futures_executor::local_pool::LocalPool::poll_pool_once::h441a98b0e037704d
                               at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:299
  33:     0x55c2bab5f427 - futures_executor::local_pool::LocalPool::poll_pool::h928133c25f7ac47f
                               at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:272
  34:     0x55c2bab5f3ea - futures_executor::local_pool::LocalPool::run::{{closure}}::hdc471c4035e02142
                               at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:151
  35:     0x55c2bab5f23e - futures_executor::local_pool::run_executor::{{closure}}::hd279b28987f27cce
                               at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:87
  36:     0x55c2bab61fad - std::thread::local::LocalKey<T>::try_with::h3f49458c9baaf860
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/thread/local.rs:263
  37:     0x55c2bab61d64 - std::thread::local::LocalKey<T>::with::hcb7e9a69ffdee9f6
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/thread/local.rs:239
  38:     0x55c2bab5f188 - futures_executor::local_pool::run_executor::ha909c8fb98d12827
                               at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:83
  39:     0x55c2bab5f3be - futures_executor::local_pool::LocalPool::run::h3b6636edf0b4f899
                               at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.4/src/local_pool.rs:151
  40:     0x55c2ba8ad79e - pubnub_core::pubnub::tests::mocked_pubnub_subscribe_ok::h892f8246e5903953
                               at pubnub-core/src/pubnub/tests.rs:188
  41:     0x55c2ba8d467a - pubnub_core::pubnub::tests::mocked_pubnub_subscribe_ok::{{closure}}::hade54f0fd319d6fa
                               at pubnub-core/src/pubnub/tests.rs:55
  42:     0x55c2ba8910ee - core::ops::function::FnOnce::call_once::h71f643a8dec7f610
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libcore/ops/function.rs:232
  43:     0x55c2ba962ee6 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h6e43b15dfd7d419c
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/liballoc/boxed.rs:1008
  44:     0x55c2ba962ee6 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h67c77219c68578ec
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/panic.rs:318
  45:     0x55c2ba962ee6 - std::panicking::try::do_call::h3a6ddbe4cd05b8c4
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/panicking.rs:331
  46:     0x55c2ba962ee6 - std::panicking::try::ha9313ec6b1fc1ba9
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/panicking.rs:274
  47:     0x55c2ba962ee6 - std::panic::catch_unwind::hfc911fe89dbda9b6
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/panic.rs:394
  48:     0x55c2ba962ee6 - test::run_test_in_process::ha46bfdf25da6fc2e
                               at src/libtest/lib.rs:541
  49:     0x55c2ba962ee6 - test::run_test::run_test_inner::{{closure}}::h0749fbe7e3187360
                               at src/libtest/lib.rs:450
  50:     0x55c2ba93af06 - std::sys_common::backtrace::__rust_begin_short_backtrace::had737a7044e3cdea
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/sys_common/backtrace.rs:130
  51:     0x55c2ba940245 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h8d5afaa1af672e3b
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/thread/mod.rs:475
  52:     0x55c2ba940245 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h068e58c8c1da81cc
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/panic.rs:318
  53:     0x55c2ba940245 - std::panicking::try::do_call::h97b0c9490af1f54e
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/panicking.rs:331
  54:     0x55c2ba940245 - std::panicking::try::hd88506813d3eede0
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/panicking.rs:274
  55:     0x55c2ba940245 - std::panic::catch_unwind::hdc25c0bc01077d90
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/panic.rs:394
  56:     0x55c2ba940245 - std::thread::Builder::spawn_unchecked::{{closure}}::h09197924846cadbf
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libstd/thread/mod.rs:474
  57:     0x55c2ba940245 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4a7c00df5764d3f3
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/libcore/ops/function.rs:232
  58:     0x55c2bab9a88a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h77d32699f8e6a85c
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/liballoc/boxed.rs:1008
  59:     0x55c2bab9a88a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hb9dc45ea0ecf1c81
                               at /rustc/a7d891e31a85269d0d0164258f2b6b6670129763/src/liballoc/boxed.rs:1008
  60:     0x55c2bab9a88a - std::sys::unix::thread::Thread::new::thread_start::hdd8a79d9dec0cadf
                               at src/libstd/sys/unix/thread.rs:87
  61:     0x7f07fdae06ba - start_thread
  62:     0x7f07fe10641d - clone
  63:                0x0 - <unknown>
```

The code is at https://github.com/pubnub/rust/blob/master/pubnub-core/src/pubnub/tests.rs
And the CI run is at: https://travis-ci.com/github/pubnub/rust/jobs/322548578

It seems like something's wrong with `mockall`. I don't exclude the possibility we're using it wrong - but the code compiles, and nothing suggests that it's on our end.

**Comment by asomers** [comment]
Try upgrading to Mockall 0.7.0.  I think this is the problem fixed by https://github.com/asomers/mockall/pull/108 .

**Comment by MOZGIII** [comment]
Thanks, I'll try it!

**Comment by asomers** [comment]
Have you gotten a chance to try 0.7.0 yet?

**Comment by MOZGIII** [comment]
Yes, the issue seems to be resolved, thx!
