### ISSUE TITLE
Unexpected Panic In Test output in mockall_derive automock::t::external_module

### ISSUE THREAD

**Issue by zancas** [asomers/mockall#127]
Hiya @asomers !

I'm really excited to use this library!

My apologies in advance if this is known/expected.

```
RUST_BACKTRACE=full cargo +nightly test -- --nocapture automock::t::external_module
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running /home/pherder/ZingOLabs/mockall/target/debug/deps/mockall_derive-e72a975dfa548d83

running 1 test
thread 'automock::t::external_module' panicked at 'automock can only mock inline modules, not modules from another file.  More information may be available when mockall is built with the "nightly" feature.', mockall_derive/src/lib.rs:72:13
stack backtrace:
   0:     0x7f087330da64 - backtrace::backtrace::libunwind::trace::h98d3444f0ad70429
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7f087330da64 - backtrace::backtrace::trace_unsynchronized::h371770250c47e40d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7f087330da64 - std::sys_common::backtrace::_print_fmt::hff04dc7e915a3c85
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7f087330da64 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h61891c439a79f00d
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f087334b96c - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x7f08732ff433 - std::io::Write::write_fmt::h1a1f8616ed2f90f9
                               at src/libstd/io/mod.rs:1537
   6:     0x7f0873312a85 - std::sys_common::backtrace::_print::h78339381acb79e1b
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f0873312a85 - std::sys_common::backtrace::print::h525aa9f9405c80a1
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f0873312a85 - std::panicking::default_hook::{{closure}}::hace90b8a218287e6
                               at src/libstd/panicking.rs:198
   9:     0x7f08733127d7 - std::panicking::default_hook::h160b6beccc49b335
                               at src/libstd/panicking.rs:218
  10:     0x7f087331313d - std::panicking::rust_panic_with_hook::h36f6804eea3f553a
                               at src/libstd/panicking.rs:481
  11:     0x7f0873312d1b - rust_begin_unwind
                               at src/libstd/panicking.rs:385
  12:     0x7f0873312c8b - std::panicking::begin_panic_fmt::hd7ab56e05bfb1154
                               at src/libstd/panicking.rs:339
  13:     0x558d8c25d681 - mockall_derive::compile_error::hf99f527438849e2d
                               at mockall_derive/src/lib.rs:72
  14:     0x558d8c242959 - mockall_derive::automock::mock_module::hb109123d9825284c
                               at mockall_derive/src/automock.rs:567
  15:     0x558d8c245a1f - mockall_derive::automock::do_automock::haf25d422e36ed068
                               at mockall_derive/src/automock.rs:665
  16:     0x558d8c1dfbdc - mockall_derive::automock::t::external_module::h40b1ffc8a1534dcf
                               at mockall_derive/src/automock.rs:734
  17:     0x558d8c27da4a - mockall_derive::automock::t::external_module::{{closure}}::h0f5544cc34706e40
                               at mockall_derive/src/automock.rs:730
  18:     0x558d8c2ba20e - core::ops::function::FnOnce::call_once::h9aec59411f59196f
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libcore/ops/function.rs:232
  19:     0x7f08735e1678 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h09e634f6e8c1141a
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/liballoc/boxed.rs:1034
  20:     0x7f08735e1678 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb267984bebe8d8d9
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libstd/panic.rs:318
  21:     0x7f08735e1678 - std::panicking::try::do_call::ha5c7b68af86e5e67
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libstd/panicking.rs:297
  22:     0x7f08735e1678 - std::panicking::try::hb44c6af65044d060
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libstd/panicking.rs:274
  23:     0x7f08735e1678 - std::panic::catch_unwind::hbd3ea99c9ad5abb8
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libstd/panic.rs:394
  24:     0x7f08735e1678 - test::run_test_in_process::h1e1b5e342158cead
                               at src/libtest/lib.rs:541
  25:     0x7f08735e1678 - test::run_test::run_test_inner::{{closure}}::h1eb5322db4b40856
                               at src/libtest/lib.rs:450
  26:     0x7f08735b5c76 - std::sys_common::backtrace::__rust_begin_short_backtrace::he688ef992bae0feb
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libstd/sys_common/backtrace.rs:130
  27:     0x7f08735bbed5 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h38c3da003e02558b
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libstd/thread/mod.rs:475
  28:     0x7f08735bbed5 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h198a8ba81ecb22d9
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libstd/panic.rs:318
  29:     0x7f08735bbed5 - std::panicking::try::do_call::hc1c0560222d2697c
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libstd/panicking.rs:297
  30:     0x7f08735bbed5 - std::panicking::try::h2905967c5b933ba1
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libstd/panicking.rs:274
  31:     0x7f08735bbed5 - std::panic::catch_unwind::h3c3adb3b710f2401
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libstd/panic.rs:394
  32:     0x7f08735bbed5 - std::thread::Builder::spawn_unchecked::{{closure}}::hc9847f404e5bc4dd
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libstd/thread/mod.rs:474
  33:     0x7f08735bbed5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha51dd5fe6928e368
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/libcore/ops/function.rs:232
  34:     0x7f08733230aa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h5b84f52b19042f22
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/liballoc/boxed.rs:1034
  35:     0x7f08733230aa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h6e1ef057e35f3144
                               at /rustc/99cb9ccb9ca2067ad6e60508e3d52da77396b2f1/src/liballoc/boxed.rs:1034
  36:     0x7f08733230aa - std::sys::unix::thread::Thread::new::thread_start::h8b0ae441dc3343d4
                               at src/libstd/sys/unix/thread.rs:87
  37:     0x7f087327f609 - start_thread
  38:     0x7f087318b103 - __clone
  39:                0x0 - <unknown>
test automock::t::external_module ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 19 filtered out

```

**Comment by asomers** [comment]
That's what's supposed to happen.  It's a `should_panic` test.  Note that the test result is `1 passed; 0 failed`.

**Comment by zancas** [comment]
:) Thanks!
